# Daniel Felipe Charry  

Para ejecutar una celda, presione **Mayús+Entrar** o haga clic en **Run (Ejecutar)** en la parte superior de la página.

<a id="section_1"></a>

## 1. Sintaxis y espacios en blanco
Python utiliza espacio con sangría para indicar el nivel de declaración. La siguiente celda es un ejemplo donde '**si**' y '**entonces**' están en el mismo nivel, mientras que '**imprimir**' está separado por espacio a un nivel diferente. El espaciado debe ser el mismo para los elementos que están en el mismo nivel.

In [1]:
student_number = input("Enter your student number:")
if int(student_number) != 0:
    print("Welcome student {}".format(student_number))
else:
    print("Try again!")

Enter your student number: 7392648736


Welcome student 7392648736


<a id='section2'></a>

## 2. Comentarios
En Python, los comentarios comienzan con numeral '#' y se extienden hasta el final de la línea. El símbolo '#' puede estar al principio de la línea o después del código. 

In [2]:
# This is code to print hello world!

print("Hello world!") # Print statement for hello world
print("# is not a comment in this case")

Hello world!
# is not a comment in this case


<a id='section3'></a>

## 3. Números y operaciones

Al igual que con otros lenguajes de programación, hay cuatro tipos de números: 
- Enteros (por ejemplo, 1, 20, 45, 1000) indicados por *ent*
- Números de coma flotante (por ejemplo, 1,25; 20,35; 1000,00) indicados por *flotante*
- Enteros largos 
- Números complejos (por ejemplo, x+2y donde se conoce x)

Operación | Resultado
----------------|-------------------------------------               
x + y | Suma de x e y	
x - y | Diferencia de x e y	
x * y | Producto de x e y	
x / y | Cociente de x e y
x // y | Cociente de x e y (piso)
x % y | Resto de x / y
abs(x) | Valor absoluto de x	
ent(x) | x convertido a entero
largo(x) | x convertido a entero largo
flotante(x) | x convertido a coma flotante	
pot(x, y) | x a la potencia y	
x ** y | x a la potencia y	

In [3]:
# Number examples
a = 5 + 8
print("Sum of int numbers: {} and number format is {}".format(a, type(a)))

b = 5 + 2.3
print ("Sum of int and {} and number format is {}".format(b, type(b)))

Sum of int numbers: 13 and number format is <class 'int'>
Sum of int and 7.3 and number format is <class 'float'>


<a id='section4'></a>

## 4. Manipulación de cadenas

Python tiene características ricas como otros lenguajes de programación para la manipulación de cadenas.

In [4]:
# Store strings in a variable
test_word = "hello world to everyone"

# Print the test_word value
print(test_word)

# Use [] to access the character of the string. The first character is indicated by '0'.
print(test_word[0])

# Use the len() function to find the length of the string
print(len(test_word))

# Some examples of finding in strings
print(test_word.count('l')) # Count number of times l repeats in the string
print(test_word.find("o")) # Find letter 'o' in the string. Returns the position of first match.
print(test_word.count(' ')) # Count number of spaces in the string
print(test_word.upper()) # Change the string to uppercase
print(test_word.lower()) # Change the string to lowercase
print(test_word.replace("everyone","you")) # Replace word "everyone" with "you"
print(test_word.title()) # Change string to title format
print(test_word + "!!!") # Concatenate strings
print(":".join(test_word)) # Add ":" between each character
print("".join(reversed(test_word))) # Reverse the string 

hello world to everyone
h
23
3
4
3
HELLO WORLD TO EVERYONE
hello world to everyone
hello world to you
Hello World To Everyone
hello world to everyone!!!
h:e:l:l:o: :w:o:r:l:d: :t:o: :e:v:e:r:y:o:n:e
enoyreve ot dlrow olleh


<a id='section5'></a>

## 5. Listas, tuplas y diccionarios

Python admite listas de tipos de datos, tuplas, diccionarios y matrices.

### Listas

Se crea una lista colocando todos los elementos (artículos) entre corchetes \[ ] separados por comas. Una lista puede tener cualquier cantidad de elementos, y pueden ser de diferentes tipos (entero, flotante, cadenas, etc.).

In [7]:
# A Python list is similar to an array. You can create an empty list too.

my_list = []

first_list = [3, 5, 7, 10]
second_list = [1, 'python', 3]

In [6]:
# Nest multiple lists
nested_list = [first_list, second_list]
nested_list

[[3, 5, 7, 10], [1, 'python', 3]]

In [8]:
# Combine multiple lists
combined_list = first_list + second_list
combined_list

[3, 5, 7, 10, 1, 'python', 3]

In [9]:
# You can slice a list, just like strings
combined_list[0:3]

[3, 5, 7]

In [10]:
# Append a new entry to the list
combined_list.append(600)
combined_list

[3, 5, 7, 10, 1, 'python', 3, 600]

In [11]:
# Remove the last entry from the list
combined_list.pop()

600

In [12]:
# Iterate the list
for item in combined_list:
    print(item)    

3
5
7
10
1
python
3


### Tuplas

Una tupla es similar a una lista, pero las usa con paréntesis ( ) en lugar de corchetes. La principal diferencia es que una tupla es inmutable, mientras que una lista es mutable.

In [13]:
my_tuple = (1, 2, 3, 4, 5)
my_tuple[1:4]

(2, 3, 4)

### Diccionarios

Un diccionario también se conoce como matriz asociativa. Un diccionario consiste en una colección de pares clave-valor. Cada par clave-valor asigna la clave a su valor asociado.

In [14]:
desk_location = {'jack': 123, 'joe': 234, 'hary': 543}
desk_location['jack']

123

<a id='section6'></a>

## 6. JSON 

JSON es texto escrito en notación de objetos JavaScript. Python tiene un paquete integrado llamado `json` que se puede usar para trabajar con datos JSON.

In [15]:
import json

# Sample JSON data
x = '{"first_name":"Jane", "last_name":"Doe", "age":25, "city":"Chicago"}'

# Read JSON data
y = json.loads(x)

# Print the output, which is similar to a dictonary
print("Employee name is "+ y["first_name"] + " " + y["last_name"])

Employee name is Jane Doe


<a id='section7'></a>

## 7. Bucles
**Bucle si, entonces, eLiF**: Python admite declaraciones condicionales como cualquier otro lenguaje de programación. Python se basa en la sangría (espacio en blanco al principio de la línea) para definir el alcance del código. 

In [16]:
a = 22
b = 33
c = 100

# if ... else example
if a > b:
    print("a is greater than b")
else:
    print("b is greater than a")
    
    
# if .. else .. elif example

if a > b:
    print("a is greater than b")
elif b > c:
    print("b is greater than c")
else:
    print("b is greater than a and c is greater than b")

b is greater than a
b is greater than a and c is greater than b


**Bucle mientras:** ejecuta un conjunto de declaraciones siempre y cuando la condición sea verdadera

In [17]:
# Sample while example
i = 1
while i < 10:
    print("count is " + str(i))
    i += 1

print("="*10)

# Continue to next iteration if x is 2. Finally, print message once the condition is false.

x = 0
while x < 5:
    x += 1
    if x == 2:
        continue
    print(x)
else:
    print("x is no longer less than 5")

count is 1
count is 2
count is 3
count is 4
count is 5
count is 6
count is 7
count is 8
count is 9
1
3
4
5
x is no longer less than 5


**Bucle para:** Un bucle `For` es más como un iterador en Python. Un bucle `For` se utiliza para iterar sobre una secuencia (lista, tupla, diccionario, conjunto, cadena o rango).

In [18]:
# Sample for loop examples
fruits = ["orange", "banana", "apple", "grape", "cherry"]
for fruit in fruits:
    print(fruit)

print("\n")
print("="*10)
print("\n")

# Iterating range
for x in range(1, 10, 2):
    print(x)
else:
    print("task complete")

print("\n")
print("="*10)
print("\n")

# Iterating multiple lists
traffic_lights = ["red", "yellow", "green"]
action = ["stop", "slow down", "go"]

for light in traffic_lights:
    for task in action:
        print(light, task)

orange
banana
apple
grape
cherry




1
3
5
7
9
task complete




red stop
red slow down
red go
yellow stop
yellow slow down
yellow go
green stop
green slow down
green go


<a id='section8'></a>

## 8. Administración de archivos
La función clave para trabajar con archivos en Python es la función `open()`. La función `open()` toma dos parámetros: nombre de archivo y modo.

Existen cuatro métodos (modos) diferentes para abrir un archivo:

- "r": Leer
- "a": Agregar
- "w": Escribir
- "x": Crear

Además, puede especificar si el archivo debe ser manejado en modo binario o texto.

- "t": Texto
- "b": Binario

In [20]:
# Let's create a test text file
!echo "This is a test file with text in it. This is the first line." > test.txt
!echo "This is the second line." >> test.txt
!echo "This is the third line." >> test.txt

In [21]:
# Read file
file = open('test.txt', 'r')
print(file.read())
file.close()

print("\n")
print("="*10)
print("\n")

# Read first 10 characters of the file
file = open('test.txt', 'r')
print(file.read(10))
file.close()

print("\n")
print("="*10)
print("\n")

# Read line from the file

file = open('test.txt', 'r')
print(file.readline())
file.close()

This is a test file with text in it. This is the first line.
This is the second line.
This is the third line.





This is a 




This is a test file with text in it. This is the first line.



In [22]:
# Create new file

file = open('test2.txt', 'w')
file.write("This is content in the new test2 file.")
file.close()

# Read the content of the new file
file = open('test2.txt', 'r')
print(file.read())
file.close()

This is content in the new test2 file.


In [23]:
# Update file
file = open('test2.txt', 'a')
file.write("\nThis is additional content in the new file.")
file.close()

# Read the content of the new file
file = open('test2.txt', 'r')
print(file.read())
file.close()

This is content in the new test2 file.
This is additional content in the new file.


In [24]:
# Delete file
import os
file_names = ["test.txt", "test2.txt"]
for item in file_names:
    if os.path.exists(item):
        os.remove(item)
        print(f"File {item} removed successfully!")
    else:
        print(f"{item} file does not exist.")

File test.txt removed successfully!
File test2.txt removed successfully!


<a id='section9'></a>

## 9. Funciones

Una función es un bloque de código que se ejecuta cuando se llama. Puede pasar datos, o *parámetros*, a la función. En Python, una función está definida por `def`.

In [25]:
# Defining a function
def new_funct():
    print("A simple function")

# Calling the function
new_funct()

A simple function


In [26]:
# Sample fuction with parameters

def param_funct(first_name):
    print(f"Employee name is {first_name}.")

param_funct("Harry")
param_funct("Larry")
param_funct("Shally")

Employee name is Harry.
Employee name is Larry.
Employee name is Shally.


**Funciones anónimas (lambda):** Una lambda es una pequeña función anónima. Una función lambda puede tomar cualquier número de argumentos, pero solo una expresión.

In [27]:
# Sample lambda example
x = lambda y: y + 100
print(x(15))

print("\n")
print("="*10)
print("\n")

x = lambda a, b: a*b/100
print(x(2,4))

115




0.08


<a id='section10'></a>

## 10. Trabajo con fecha y hora 

Se puede usar un módulo `datetime` en Python para trabajar con objetos de fecha.

In [28]:
import datetime

x = datetime.datetime.now()

print(x)
print(x.year)
print(x.strftime("%A"))
print(x.strftime("%B"))
print(x.strftime("%d"))
print(x.strftime("%H:%M:%S %p"))

2026-09-14 22:43:48.151511
2026
Monday
September
14
22:43:48 PM


<a id='section11'></a>

## 11. NumPy

NumPy es el paquete fundamental para la informática científica con Python. Entre otras cosas, contiene:

- Potente objeto de matriz N-dimensional
- Funciones sofisticadas (radiodifusión)
- Herramientas para integrar código C/C ++ y Fortran
- Álgebra lineal útil, transformada de Fourier y capacidades de números aleatorios

In [29]:
# Install NumPy using pip
!pip install --upgrade pip
!pip install numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 67.7 MB/s  0:00:00
  Attempting uninstall: pip
    Found existing installation: pip 26.2
    Uninstalling pip-26.2:
      Successfully uninstalled pip-26.2


In [30]:
# Import NumPy module
import numpy as np

### Inspección de la matriz

In [31]:
# Create array
a = np.arange(15).reshape(3, 5) # Create array with range 0-14 in 3 by 5 dimension
b = np.zeros((3,5)) # Create array with zeroes
c = np.ones( (2,3,4), dtype=np.int16 ) # Createarray with ones and defining data types
d = np.ones((3,5))

In [32]:
a.shape # Array dimension

(3, 5)

In [33]:
len(b)# Length of array

3

In [34]:
c.ndim # Number of array dimensions

3

In [35]:
a.size # Number of array elements

15

In [36]:
b.dtype # Data type of array elements

dtype('float64')

In [37]:
c.dtype.name # Name of data type

'int16'

In [38]:
c.astype(float) # Convert an array type to a different type

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

### Operaciones matemáticas básicas

In [39]:
# Create array
a = np.arange(15).reshape(3, 5) # Create array with range 0-14 in 3 by 5 dimension
b = np.zeros((3,5)) # Create array with zeroes
c = np.ones( (2,3,4), dtype=np.int16 ) # Createarray with ones and defining data types
d = np.ones((3,5))

In [40]:
np.add(a,b) # Addition

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [41]:
np.subtract(a,b) # Substraction

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [42]:
np.divide(a,d) # Division

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [43]:
np.multiply(a,d) # Multiplication

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.]])

In [44]:
np.array_equal(a,b) # Comparison - arraywise

False

### Aggregate functions

In [45]:
# Create array
a = np.arange(15).reshape(3, 5) # Create array with range 0-14 in 3 by 5 dimension
b = np.zeros((3,5)) # Create array with zeroes
c = np.ones( (2,3,4), dtype=np.int16 ) # Createarray with ones and defining data types
d = np.ones((3,5))

In [46]:
a.sum() # Array-wise sum

np.int64(105)

In [47]:
a.min() # Array-wise min value

np.int64(0)

In [48]:
a.mean() # Array-wise mean

np.float64(7.0)

In [49]:
a.max(axis=0) # Max value of array row

array([10, 11, 12, 13, 14])

In [50]:
np.std(a) # Standard deviation

np.float64(4.320493798938574)

### Subconfiguración, intervalos e indexación

In [51]:
# Create array
a = np.arange(15).reshape(3, 5) # Create array with range 0-14 in 3 by 5 dimension
b = np.zeros((3,5)) # Create array with zeroes
c = np.ones( (2,3,4), dtype=np.int16 ) # Createarray with ones and defining data types
d = np.ones((3,5))

In [52]:
a[1,2] # Select element of row 1 and column 2

np.int64(7)

In [53]:
a[0:2] # Select items on index 0 and 1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
a[:1] # Select all items at row 0

array([[0, 1, 2, 3, 4]])

In [55]:
a[-1:] # Select all items from last row

array([[10, 11, 12, 13, 14]])

In [56]:
a[a<2] # Select elements from 'a' that are less than 2

array([0, 1])

### Manipulación de matriz

In [57]:
# Create array
a = np.arange(15).reshape(3, 5) # Create array with range 0-14 in 3 by 5 dimension
b = np.zeros((3,5)) # Create array with zeroes
c = np.ones( (2,3,4), dtype=np.int16 ) # Createarray with ones and defining data types
d = np.ones((3,5))

In [58]:
np.transpose(a) # Transpose array 'a'

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [59]:
a.ravel() # Flatten the array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
a.reshape(5,-2) # Reshape but don't change the data

In [ ]:
np.append(a,b) # Append items to the array

In [ ]:
np.concatenate((a,d), axis=0) # Concatenate arrays

In [ ]:
np.vsplit(a,3) # Split array vertically at 3rd index

In [ ]:
np.hsplit(a,5) # Split array horizontally at 5th index

<a id='section12'></a>

## Pandas

Pandas es una biblioteca de código abierto con licencia BSD que proporciona estructuras de datos y herramientas de análisis de datos fáciles de usar y de alto rendimiento para el lenguaje de programación Python.

Los DataFrames de Pandas son la representación en memoria más utilizada de colecciones de datos complejas dentro de Python.

In [ ]:
# Install pandas, xlrd, and openpyxl using pip
!pip install pandas
!pip install xlrd openpyxl

In [ ]:
# Import NumPy and Pandas modules
import numpy as np
import pandas as pd

In [ ]:
# Sample dataframe df
df = pd.DataFrame({'num_legs': [2, 4, np.nan, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, np.nan, 1, 8]},
                   index=['falcon', 'dog', 'spider', 'fish'])
df # Display dataframe df

In [ ]:
# Another sample dataframe df1 - using NumPy array with datetime index and labeled column
df1 = pd.date_range('20130101', periods=6)
df1 = pd.DataFrame(np.random.randn(6, 4), index=df1, columns=list('ABCD'))
df1 # Display dataframe df1

### Visualización de los datos

In [ ]:
df1 = pd.date_range('20130101', periods=6)
df1 = pd.DataFrame(np.random.randn(6, 4), index=df1, columns=list('ABCD'))

In [ ]:
df1.head(2) # View top data

In [ ]:
df1.tail(2) # View bottom data

In [ ]:
df1.index # Display index column

In [ ]:
df1.dtypes # Inspect datatypes

In [ ]:
df1.describe() # Display quick statistics summary of data

### Subconfiguración, intervalos e indexación

In [ ]:
df1 = pd.date_range('20130101', periods=6)
df1 = pd.DataFrame(np.random.randn(6, 4), index=df1, columns=list('ABCD'))

In [ ]:
df1.T # Transpose data

In [ ]:
df1.sort_index(axis=1, ascending=False) # Sort by an axis

In [ ]:
df1.sort_values(by='B') # Sort by values

In [ ]:
df1['A'] # Select column A

In [ ]:
df1[0:3] # Select index 0 to 2

In [ ]:
df1['20130102':'20130104'] # Select from index matching the values

In [ ]:
df1.loc[:, ['A', 'B']] # Select on a multi-axis by label

In [ ]:
df1.iloc[3] # Select via the position of the passed integers

In [ ]:
df1[df1 > 0] # Select values from a DataFrame where a boolean condition is met

In [ ]:
df2 = df1.copy() # Copy the df1 dataset to df2
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three'] # Add column E with value
df2[df2['E'].isin(['two', 'four'])] # Use isin method for filtering

### Pérdida de datos

Pandas utiliza principalmente el valor `np.nan` para representar los datos faltantes. No está incluido en los cálculos de forma predeterminada.

In [ ]:
df = pd.DataFrame({'num_legs': [2, 4, np.nan, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, np.nan, 1, 8]},
                   index=['falcon', 'dog', 'spider', 'fish'])

In [ ]:
df.dropna(how='any') # Drop any rows that have missing data

In [ ]:
df.dropna(how='any', axis=1) # Drop any columns that have missing data

In [ ]:
df.fillna(value=5) # Fill missing data with value 5

In [ ]:
pd.isna(df) # To get boolean mask where data is missing

### Administración de archivos

In [ ]:
df = pd.DataFrame({'num_legs': [2, 4, np.nan, 0],
                   'num_wings': [2, 0, 0, 0],
                   'num_specimen_seen': [10, np.nan, 1, 8]},
                   index=['falcon', 'dog', 'spider', 'fish'])

In [ ]:
df.to_csv('foo.csv') # Write to CSV file

In [ ]:
pd.read_csv('foo.csv') # Read from CSV file

In [ ]:
df.to_excel('foo.xlsx', sheet_name='Sheet1') # Write to Microsoft Excel file

In [ ]:
pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA']) # Read from Microsoft Excel file

### Trazado

In [ ]:
# Install Matplotlib using pip
!pip install matplotlib

In [ ]:
from matplotlib import pyplot as plt # Import Matplotlib module

In [ ]:
# Generate random time-series data
ts = pd.Series(np.random.randn(1000),index=pd.date_range('1/1/2000', periods=1000)) 
ts.head()

In [ ]:
ts = ts.cumsum()
ts.plot() # Plot graph
plt.show()

In [ ]:
# On a DataFrame, the plot() method is convenient to plot all of the columns with labels
df4 = pd.DataFrame(np.random.randn(1000, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df4 = df4.cumsum()
df4.head()

In [ ]:
df4.plot()
plt.show()